### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by alexdriaguine** [alexdriaguine/string-replace-loader#1]
Add an MIT license

**Comment by minimalistdev** [comment]
This is a good first issue for me, can I try?

**Comment by alexdriaguine** [comment]
Absolutely, it's yours @cfsbsi :)

**Comment by minimalistdev** [comment]
I need to know the full name of the repository owner

**Comment by alexdriaguine** [comment]
Alexandre Driaguine

**Comment by pheliperocha** [comment]
Oh sorry, I made a PR right now and didn't see it was assigned already.

**Comment by alexdriaguine** [comment]
No worries! I'll merge @cfsbsi PR though since he was first to claim it :)

**Comment by pheliperocha** [comment]
Okay

**Comment by cfsbsi** [comment]
#3

**Comment by minimalistdev** [comment]
It's done on #3
